@hagglehaul.Server_HostAddress = http://localhost:5250
@hagglehaul.Api_Base = api

GET {{hagglehaul.Server_HostAddress}}/{{hagglehaul.Api_Base}}/weatherforecast/
Accept: application/json

###

POST {{hagglehaul.Server_HostAddress}}/{{hagglehaul.Api_Base}}/authentication/login/
Accept: application/json

###

POST {{hagglehaul.Server_HostAddress}}/{{hagglehaul.Api_Base}}/authentication/register/
Accept: application/json

###

GET {{hagglehaul.Server_HostAddress}}/{{hagglehaul.Api_Base}}/mongotest/insecure/
Accept: application/json

###

GET {{hagglehaul.Server_HostAddress}}/{{hagglehaul.Api_Base}}/mongotest/secure/
Accept: application/json

###
