@hagglehaul.Server_HostAddress = http://localhost:5250

GET {{hagglehaul.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{hagglehaul.Server_HostAddress}}/authentication/login/
Accept: application/json

###

GET {{hagglehaul.Server_HostAddress}}/mongotest/insecure/
Accept: application/json

###

GET {{hagglehaul.Server_HostAddress}}/mongotest/secure/
Accept: application/json

###
